[package]
name = "jenny-derive"
version = "0.1.0"
authors = ["mrobakowski"]

[dependencies]
jni = "0.6.0"
lazy_static = "0.2.8"
syn = { version = "0.11.11", features = ["parsing", "printing", "full"] }
quote = "0.3.15"
case = "0.1.0"

[lib]
proc-macro = true